FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04
RUN apt update && apt upgrade -y && apt install -y python3 python3-pip ffmpeg
WORKDIR /work
RUN pip install --break-system-packages faster-whisper
RUN mkdir source res
RUN python3 -c 'from faster_whisper import WhisperModel; WhisperModel("large-v3-turbo")'

COPY ./main.py main.py
COPY <<-EOF run.sh
rm source/* -f
python3 main.py
EOF
RUN chmod a+x run.sh
CMD ["./run.sh"]
