FROM rust:latest

RUN apt update && \
    apt install -y wget gnupg lsb-release software-properties-common

RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 20

RUN apt install -y build-essential cmake pkg-config git \
    llvm-20 llvm-20-dev \
    mlir-20 mlir-20-dev && \
    rustup update

WORKDIR /workspace
ENV MLIR_SYS_200_PREFIX=/usr/lib/llvm-20
ENV LLVM_SYS_201_PREFIX=/usr/lib/llvm-20
ENV TABLEGEN_200_PREFIX=/usr/lib/llvm-20

RUN git clone https://github.com/lambdaclass/concrete.git

WORKDIR /workspace/concrete

RUN cargo build --release
